networks:
  backend:

volumes:
  pgdata:
  appdata:
  csvdata:
  node_data:

services:
  db:
    image: postgres:16
    container_name: iss_db
    environment:
      POSTGRES_DB: monolith
      POSTGRES_USER: monouser
      POSTGRES_PASSWORD: monopass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monouser -d monolith"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - backend
    ports:
      - "5432:5432"

  rust_iss:
    build:
      context: ./services/rust-iss
    container_name: rust_iss
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://monouser:monopass@db:5432/monolith}
      NASA_API_URL: ${NASA_API_URL:-}
      NASA_API_KEY: ${NASA_API_KEY:-}
      FETCH_EVERY_SECONDS: ${FETCH_EVERY_SECONDS:-600}
      WHERE_ISS_URL: ${WHERE_ISS_URL:-https://api.wheretheiss.at/v1/satellites/25544}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "8081:3000"

  node_app:
    build:
      context: services/node-app
    container_name: node_app
    env_file:
      - .env  # Используем общий .env файл из корня
    environment:
      NODE_ENV: production
      PORT: 3000
      RUST_BASE: http://rust_iss:3000
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: monolith
      DB_USERNAME: monouser
      DB_PASSWORD: monopass
      REDIS_URL: redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      rust_iss:
        condition: service_started
      redis:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend
    volumes:
      - node_data:/app/public/uploads

  nginx:
    image: nginx:1.27-alpine
    container_name: web_nginx
    depends_on:
      node_app:
        condition: service_healthy
    volumes:
      - ./services/node-app/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend
    ports:
      - "8080:80"

  pascal_legacy:
    build:
      context: ./services/pascal-legacy
    container_name: pascal_legacy
    environment:
      CSV_OUT_DIR: /data/csv
      GEN_PERIOD_SEC: ${PAS_LEGACY_PERIOD:-300}
      PGHOST: db
      PGPORT: 5432
      PGUSER: monouser
      PGPASSWORD: monopass
      PGDATABASE: monolith
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - csvdata:/data/csv
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3